### ISSUE TITLE
No way to run with default upstream west.yml

### ISSUE THREAD

**Issue by mon** [zephyrproject-rtos/action-zephyr-setup#18]
For my project, I init west with just `west init --mr v3.5.0`. I can probably do without the `--mr` flag, but since `action-zephyr-setup` adds the `-l` flag, init fails because it makes west look for an explicit west.yml before checking out zephyr.

I'm pretty new to zephyr, so I'm not sure of the most idiomatic solution
- Make the `app-path` input optional
- My setup is actually wrong, and I should be committing a `west.yml` to my repository
- I should add a fetch step in my workflow to get the default .yml before running `action-zephyr-setup`

**Comment by fabiobaltieri** [comment]
Yeah the action is really meant to the workspace type of application layout, I'd suggest adding a west manifest to your application so that you can also add a module allowlist and make the checkout a lot faster by dropping the modules that you don't need, but if you really don't want to you should be able to add an extra `actions/checkout` check to your workflow to fetch the zephyr repository manually and then have the workflow do only the modules, it's sort-of how the upstream test works (https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/workflows/hello_world_multiplatform.yaml).

**Comment by mon** [comment]
Excellent! Thanks for the clarification, I'll do a manual checkout step for now and move to a custom west.yml once I've worked out which modules I'm keeping around.
